In [1]:
import pandas as pd
import numpy as np

In [8]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm,tree
from sklearn.model_selection import train_test_split

In [9]:
data=pd.read_csv("Iris.csv")

In [10]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [12]:
X = data[['sepal_length','sepal_width','petal_length']]

In [13]:
y= data['species']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, shuffle=True)

In [15]:
classifiers=[]

In [16]:
Model1=svm.SVC()
classifiers.append(Model1)

In [17]:
Model2 = tree.DecisionTreeClassifier()
classifiers.append(Model2)

In [18]:
Model3 = RandomForestClassifier()
classifiers.append(Model3)

In [23]:
for clf in classifiers:
    clf.fit(X_train, y_train)
    y_pred= clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print("Accuracy of %s is %s"%(clf, acc))
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix of %s is %s"%(clf, cm))

Accuracy of SVC() is 0.9777777777777777
Confusion Matrix of SVC() is [[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]
Accuracy of DecisionTreeClassifier() is 0.9333333333333333
Confusion Matrix of DecisionTreeClassifier() is [[13  0  0]
 [ 0 18  2]
 [ 0  1 11]]
Accuracy of RandomForestClassifier() is 0.9555555555555556
Confusion Matrix of RandomForestClassifier() is [[13  0  0]
 [ 0 19  1]
 [ 0  1 11]]


In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [26]:
Model4 = LogisticRegression()
Model4.fit(X_train, y_train)
classifiers.append(Model4)

In [27]:
for clf in classifiers:
    clf.fit(X_train, y_train)
    y_pred= clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print("Accuracy of %s is %s"%(clf, acc))
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix of %s is %s"%(clf, cm))

Accuracy of SVC() is 0.9777777777777777
Confusion Matrix of SVC() is [[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]
Accuracy of DecisionTreeClassifier() is 0.9333333333333333
Confusion Matrix of DecisionTreeClassifier() is [[13  0  0]
 [ 0 18  2]
 [ 0  1 11]]
Accuracy of RandomForestClassifier() is 0.9333333333333333
Confusion Matrix of RandomForestClassifier() is [[13  0  0]
 [ 0 18  2]
 [ 0  1 11]]
Accuracy of LogisticRegression() is 0.9777777777777777
Confusion Matrix of LogisticRegression() is [[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]


In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
Model5=KNeighborsClassifier(n_neighbors=3)
Model5.fit(X_train, y_train)
classifiers.append(Model5)

In [30]:
for clf in classifiers:
    clf.fit(X_train, y_train)
    y_pred= clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print("Accuracy of %s is %s"%(clf, acc))
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix of %s is %s"%(clf, cm))

Accuracy of SVC() is 0.9777777777777777
Confusion Matrix of SVC() is [[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]
Accuracy of DecisionTreeClassifier() is 0.9333333333333333
Confusion Matrix of DecisionTreeClassifier() is [[13  0  0]
 [ 0 18  2]
 [ 0  1 11]]
Accuracy of RandomForestClassifier() is 0.9777777777777777
Confusion Matrix of RandomForestClassifier() is [[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]
Accuracy of LogisticRegression() is 0.9777777777777777
Confusion Matrix of LogisticRegression() is [[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]
Accuracy of KNeighborsClassifier(n_neighbors=3) is 0.9333333333333333
Confusion Matrix of KNeighborsClassifier(n_neighbors=3) is [[13  0  0]
 [ 0 17  3]
 [ 0  0 12]]


In [31]:
from sklearn.naive_bayes import GaussianNB

In [32]:
Model6= GaussianNB()
Model6.fit(X_train, y_train)
classifiers.append(Model6)

In [33]:
for clf in classifiers:
    clf.fit(X_train, y_train)
    y_pred= clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print("Accuracy of %s is %s"%(clf, acc))
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix of %s is %s"%(clf, cm))

Accuracy of SVC() is 0.9777777777777777
Confusion Matrix of SVC() is [[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]
Accuracy of DecisionTreeClassifier() is 0.9333333333333333
Confusion Matrix of DecisionTreeClassifier() is [[13  0  0]
 [ 0 18  2]
 [ 0  1 11]]
Accuracy of RandomForestClassifier() is 0.9333333333333333
Confusion Matrix of RandomForestClassifier() is [[13  0  0]
 [ 0 18  2]
 [ 0  1 11]]
Accuracy of LogisticRegression() is 0.9777777777777777
Confusion Matrix of LogisticRegression() is [[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]
Accuracy of KNeighborsClassifier(n_neighbors=3) is 0.9333333333333333
Confusion Matrix of KNeighborsClassifier(n_neighbors=3) is [[13  0  0]
 [ 0 17  3]
 [ 0  0 12]]
Accuracy of GaussianNB() is 0.9555555555555556
Confusion Matrix of GaussianNB() is [[13  0  0]
 [ 0 19  1]
 [ 0  1 11]]
